# Generated by Django 5.2.11 on 2026-04-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('movies', '0002_alter_movie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='movies',
            field=models.ManyToManyField(blank=True, null=True, to='movies.movie'),
        ),
    ]
