# Generated by Django 5.2.11 on 2026-04-06

from django.db import migrations

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    editor_group, _ = Group.objects.get_or_create(name='Editors')
    viewer_group, _ = Group.objects.get_or_create(name='Viewers')

    movie_ct, _ = ContentType.objects.get_or_create(app_label='movies', model='movie')
    director_ct, _ = ContentType.objects.get_or_create(app_label='directors', model='director')
    list_ct, _ = ContentType.objects.get_or_create(app_label='lists', model='list')

    def ensure_permission(ct, codename, name):
        Permission.objects.get_or_create(
            content_type=ct,
            codename=codename,
            defaults={'name': name}
        )

    for ct, model_name in [(movie_ct, 'movie'), (director_ct, 'director'), (list_ct, 'list')]:
        for action in ['add', 'change', 'delete', 'view']:
            ensure_permission(ct, f'{action}_{model_name}', f'Can {action} {model_name}')


    editor_movie_perms = Permission.objects.filter(
        content_type=movie_ct, 
        codename__in=['add_movie', 'change_movie', 'delete_movie', 'view_movie']
    )
    editor_director_perms = Permission.objects.filter(
        content_type=director_ct, 
        codename__in=['add_director', 'change_director', 'delete_director', 'view_director']
    )
    all_list_perms = Permission.objects.filter(content_type=list_ct)

    editor_group.permissions.set(list(editor_movie_perms) + list(editor_director_perms) + list(all_list_perms))


    viewer_movie_perms = Permission.objects.filter(content_type=movie_ct, codename='view_movie')
    viewer_director_perms = Permission.objects.filter(content_type=director_ct, codename='view_director')
    
    viewer_group.permissions.set(list(viewer_movie_perms) + list(viewer_director_perms) + list(all_list_perms))

def remove_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['Editors', 'Viewers']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_movies'),
        ('movies', '0002_alter_movie_title'),
        ('directors', '0002_alter_director_name'),
        ('lists', '0004_list_user'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(create_groups, remove_groups),
    ]
