# Generated by Django 5.2.11 on 2026-04-06

from django.db import migrations

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # Define groups
    editor_group, _ = Group.objects.get_or_create(name='Editors')
    viewer_group, _ = Group.objects.get_or_create(name='Viewers')

    # Get Content Types
    # It's better to fetch by app_label and model to avoid issues in migrations
    movie_ct = ContentType.objects.get(app_label='movies', model='movie')
    director_ct = ContentType.objects.get(app_label='directors', model='director')
    list_ct = ContentType.objects.get(app_label='lists', model='list')

    # Editor permissions
    # Movies & Directors: Full CRUD (Add, Change, Delete, View)
    # Lists: All permissions
    editor_movie_perms = Permission.objects.filter(
        content_type=movie_ct, 
        codename__in=['add_movie', 'change_movie', 'delete_movie', 'view_movie']
    )
    editor_director_perms = Permission.objects.filter(
        content_type=director_ct, 
        codename__in=['add_director', 'change_director', 'delete_director', 'view_director']
    )
    all_list_perms = Permission.objects.filter(content_type=list_ct)

    editor_group.permissions.set(list(editor_movie_perms) + list(editor_director_perms) + list(all_list_perms))

    # Viewer permissions
    # Movies & Directors: View only
    # Lists: All permissions
    viewer_movie_perms = Permission.objects.filter(content_type=movie_ct, codename='view_movie')
    viewer_director_perms = Permission.objects.filter(content_type=director_ct, codename='view_director')
    
    viewer_group.permissions.set(list(viewer_movie_perms) + list(viewer_director_perms) + list(all_list_perms))

def remove_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['Editors', 'Viewers']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_movies'),
        ('movies', '0002_alter_movie_title'),
        ('directors', '0002_alter_director_name'),
        ('lists', '0004_list_user'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(create_groups, remove_groups),
    ]
