# Generated by Django 5.2.11 on 2026-02-23 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, 'Enter a name for the director with at least three characters. Example: McG.')]),
        ),
    ]
