# Generated by Django 5.2.11 on 2026-02-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='lists', to='movies.movie'),
        ),
    ]
