# Generated by Django 5.2.11 on 2026-02-23 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_alter_list_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, 'Enter a name for the list with at least three characters. Example: Fav')]),
        ),
    ]
