# Generated by Django 5.2.11 on 2026-02-22 01:17

import common.validators
import django.core.validators
import django.db.models.deletion
import movies.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(1)])),
                ('tagline', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True, validators=[common.validators.validate_description_length])),
                ('release_year', models.IntegerField(validators=[movies.validators.validate_release_year])),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Sci-Fi', 'Sci-Fi'), ('Romance', 'Romance'), ('Thriller', 'Thriller'), ('Fantasy', 'Fantasy'), ('Animation', 'Animation'), ('Documentary', 'Documentary'), ('Crime', 'Crime'), ('Adventure', 'Adventure'), ('Mystery', 'Mystery'), ('Family', 'Family'), ('History', 'History'), ('Music', 'Music'), ('War', 'War'), ('Western', 'Western')], max_length=20)),
                ('image_url', models.URLField()),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('runtime', models.IntegerField(validators=[movies.validators.validate_runtime_positive])),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='directors.director')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('title', 'release_year'), name='unique_movie')],
            },
        ),
    ]
