# Generated by Django 5.2.11 on 2026-02-23 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(1, 'Provide at least one character for a title. Example: X')]),
        ),
    ]
